name: senfonico
favicon: null
layout_spectrum: 0.2579
typography_spectrum: 0.46419
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 1
  lightness: 0.741720023099333
  saturation: 0.34504548856057227
  rhythmicContrast: 0
purpose: []
