name: senfonico
favicon: null
layout_spectrum: 0.9767421749420464
typography_spectrum: 0.5629282023292035
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.8469574723858386
  lightness: 0.741720023099333
  saturation: 0.34504548856057227
  rhythmicContrast: 0.12630290258675814
purpose: []
